services:
  openrefine:
    environment:
      REFINE_MEMORY: 2000M
      REFINE_MIN_MEMORY: 2000M
    image: ghcr.io/ninanor/openrefine:master
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3333
      published: 3333
      protocol: tcp
    volumes:
    - type: bind
      source: ./workspace
      target: /workspace
      # bind:
      #   create_host_path: true
  openrefine_2:
    environment:
      REFINE_MEMORY: 2000M
      REFINE_MIN_MEMORY: 2000M
    image: ghcr.io/ninanor/openrefine:master
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3333
      published: 3334
      protocol: tcp
    volumes:
    - type: bind
      source: ./workspace
      target: /workspace
      # bind:
      #   create_host_path: true
  openrefine_3:
    environment:
      REFINE_MEMORY: 2000M
      REFINE_MIN_MEMORY: 2000M
    image: ghcr.io/ninanor/openrefine:master
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3333
      published: 3335
      protocol: tcp
    volumes:
    - type: bind
      source: ./workspace
      target: /workspace
      # bind:
      #   create_host_path: true
  openrefine_4:
    environment:
      REFINE_MEMORY: 2000M
      REFINE_MIN_MEMORY: 2000M
    image: ghcr.io/ninanor/openrefine:master
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3333
      published: 3336
      protocol: tcp
    volumes:
    - type: bind
      source: ./workspace
      target: /workspace
      # bind:
      #   create_host_path: true
  openrefine_5:
    environment:
      REFINE_MEMORY: 2000M
      REFINE_MIN_MEMORY: 2000M
    image: ghcr.io/ninanor/openrefine:master
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3333
      published: 3337
      protocol: tcp
    volumes:
    - type: bind
      source: ./workspace
      target: /workspace
      # bind:
      #   create_host_path: true
networks:
  default:
    name: openrefine_default
